name: ReleaseCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Backup to S3
      run: timestamp=$(date +%s) && bash scripts/pipeline/release.sh test-github-action-duongtt "folderbackup/myapp_${timestamp}.zip" AWS_ACCESS_KEY AWS_SECRERT_KEY "myapp.zip"
