name: ReleaseCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Backup to S3
      run: timestamp=$(date +%s) && bash scripts/pipeline/release.sh test-github-action-duongtt "folderbackup/myapp_${timestamp}.zip" AKIAQHN5IJ2GEVLZZ4M3 XuCkWlJ5zofoYN1zekbOJzU0h6HYwDp6jHtmXx1e "myapp.zip"